"""FastAPI Router for Premier League Endpoints in ennovera-pl."""
from typing import Optional, List, Dict, Any
from fastapi import APIRouter, HTTPException, Query
from app.services.pl_service import pl_service
from app.schemas.pl import PLFixturePrediction

router = APIRouter(prefix="/api/v1/pl", tags=["Premier League"])

@router.get("/fixtures", response_model=List[PLFixturePrediction])
def get_fixtures(
    gw: int = Query(1, ge=1, le=38, description="Premier League Gameweek (1-38)"),
    season: str = Query("2025-26", description="Season calendar")
):
    """Retrieve fixture predictions for a specific gameweek generated by CORE_BASE."""
    return pl_service.get_gameweek_fixtures(season=season, gw=gw)

@router.get("/predict", response_model=PLFixturePrediction)
def predict_fixture(
    home: str = Query(..., description="Home club name"),
    away: str = Query(..., description="Away club name"),
    gw: Optional[int] = Query(None, ge=1, le=38, description="Gameweek number"),
    season: str = Query("2025-26", description="Season calendar")
):
    """Generate real-time CORE_BASE prediction for any club pairing."""
    if not home or not away or home.strip().lower() == away.strip().lower():
        raise HTTPException(status_code=400, detail="Home and away teams must be distinct clubs.")
    return pl_service.predict_match(home, away, season=season, gw=gw)
